# Generated by Django 5.0.2 on 2024-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=False)),
                ('type', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=200)),
                ('referal_code', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
