# Generated by Django 5.0.2 on 2024-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
