# Generated by Django 5.0.2 on 2024-02-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('referal_amnt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('other_amnt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='users.customers')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
