# Generated by Django 5.0.2 on 2024-02-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentOpt', '0002_alter_investmentoption_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentoption',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
