# Generated by Django 5.0.2 on 2024-02-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investmentOpt', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='investmentOpt.investmentoption')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.customers')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
